version: '3.3'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    user: '${USER_ID}:${GROUP_ID}'
    restart: unless-stopped
    image: grafikart/php:php8.1-1
    build:
      context: ./tools/docker/php
    volumes:
      - .:/var/www:delegated
    environment:
      APP_ENV: dev
volumes:
  node-data:
    driver: local
  search-data:
    driver: local

networks:
  dev:
